#define SIRE_UNAME     "Linux"
#define SIRE_HOST      "FunBox"
#define SIRE_HARDWARE  "i686"
#define SIRE_UMRKISS   "2.6.27-17-generic"
#define SIRE_UMARK     "2"
#define SIRE_UISSUE    "6"
#define SIRE_UREV      "27-17-generic"
#define SIRE_OSTYPE    "Linux"
#define SIRE_MACHINE   "INTEL_LINUX"
#define INTEL_LINUX  1
#define SIRE_PLATFORM  "posix"
#define SIRE_DATE      "10/05/14 16:02:28"
#define SIRE_PATH      "/home/david/Projects/sire-4_0c/sire"
